#!/bin/sh

set -eu

umask 027

if ! [ -d ~/.vim/colors ]; then
    mkdir -p ~/.vim/colors
fi


cp .vimrc                       ~/.vimrc
cp .vim/0.vim                   ~/.vim/
cp .vim/statusline_defs.vim     ~/.vim/
cp .vim/statusline_defs.lua     ~/.vim/
cp .vim/colors/*.vim ~/.vim/colors/
